# Site settings
title: "Altcoin Trading"
subtitle: "The forex of cryptocurrencies, bitcoin as the base."
description: "Altcoin Trading is the forex of cryptocurrencies, with bitcoin as the base currency."
baseurl: ""
url: "https://www.altcointrading.net"
# url: http://localhost:4000

author: "AltcoinTrading"
# Build settings
markdown: kramdown
## Default image size: 700x360

ads:
  ledger: '<div class="text-center">
  <a rel="nofollow" target="_blank" href="https://www.ledgerwallet.com/r/e274">
  <amp-img itemprop="image" alt="Ledger Wallet protects your bitcoins"
  src="https://www.ledgerwallet.com/images/promo/ledger-468x90-01.jpg"
  layout="responsive"
  data-original-width="468px" data-original-height="90px"
  width="468px" height="90px"></amp-img>
  </a></div>'
  ledger-thin: '<div class="text-center">
  <a rel="nofollow" target="_blank" href="https://www.ledgerwallet.com/r/e274">
  <amp-img itemprop="image" alt="Ledger Wallet protects your bitcoins"
  src="/img/wallets/ledger-hero.png"
  layout="responsive"
  data-original-width="710px" data-original-height="60px"
  width="710px" height="60px"></amp-img>
  </a></div><br>'
  trezor: '<div class="shifted-left">
  <a rel="nofollow" target="_blank" href="https://shop.trezor.io?a=fany@tutanota.com">
  <amp-img itemprop="image"
  src="https://www.altcointrading.net/img/wallets/trezor.jpg"
  alt="Trezor Wallet for bitcoins and altcoins" data-original-width="728px"
  data-original-height="90px" layout="responsive" width="728px" height="90px">
  </amp-img></a></div>'
  trezorbox: '<div class="text-center">
  <a rel="nofollow" target="_blank" href="https://shop.trezor.io?a=fany@tutanota.com">
  <amp-img itemprop="image"
  src="/img/wallets/trezor-altcoins.jpg"
  alt="Trezor Wallet for bitcoins and altcoins" data-original-width="350px"
  data-original-height="320px" layout="responsive" width="350px" height="320px">
  </amp-img></a></div>'
  trezorlong: '<div class="text-center">
  <a rel="nofollow" target="_blank" href="https://shop.trezor.io?a=fany@tutanota.com">
  <amp-img itemprop="image"
  src="/img/wallets/trezor-altcoins-long.jpg"
  alt="Trezor Wallet for bitcoins and altcoins" data-original-width="728px"
  data-original-height="90px" layout="responsive" width="728px" height="90px">
  </amp-img></a></div>'
  pm1: '<div class="text-center"><a rel="nofollow" target="_blank" href="https://perfectmoney.is/?ref=7622697">
  <amp-img itemprop="image" alt="Perfect Money" src="/img/ads/pm1.jpg"
  data-original-width="468px" data-original-height="20px" layout="responsive" width="468px" height="20px">
  </amp-img></a></div>'
  pm2: '<div class="shifted-left"><a rel="nofollow" target="_blank" href="https://perfectmoney.is/?ref=7622697">
  <amp-img itemprop="image" alt="Perfect Money" src="/img/ads/pm2.jpg"
  data-original-width="468px" data-original-height="20px" layout="responsive" width="468px" height="20px"></amp-img>
  </a></div>'
  acash: '<div class="containter-center"><a href="http://wallet.advcash.com/referral/3d50b494-473e-45e5-8434-5ad9d8658cc8" rel="nofollow" target="_blank"><amp-img itemprop="image" src="/img/vcc/acash.png" alt="AdvCash Bitcoin Virtual Credit Card" data-original-width="336px" data-original-height="300px" layout="responsive" width="336px" height="300px"></amp-img></a></div>'
  acashgreen: '<div class="containter-center"><a href="http://wallet.advcash.com/referral/3d50b494-473e-45e5-8434-5ad9d8658cc8" rel="nofollow" target="_blank"><amp-img itemprop="image" src="/img/vcc/acash_green.jpeg" alt="AdvCash Bitcoin Virtual Credit Card" data-original-width="336px" data-original-height="300px" layout="responsive" width="336px" height="300px"></amp-img></a></div>'
  aads728: '<div class="shifted-left">
  <iframe data-aa="147076" src="https://ad.a-ads.com/147076?size=728x90" scrolling="no" style="width:728px; height:90px; border:0px; padding:0;overflow:hidden" allowtransparency="true" frameborder="0"></iframe>
  </div>'
  feeds: '<div class="gt_newpost" style="padding: 20px; outline: 0px none; vertical-align: baseline; background: rgb(255, 255, 255) none repeat scroll 0% 0%; font-size: 100%; box-shadow: 0px 0px 5px rgb(204, 204, 204); display: inline-table; width: 240px; height: auto;"> <div class="form-overlay"></div> <form method="post" target="popupwindow" action="http://www.specificfeeds.com/widgets/subscribeWidget/dWZIOCtQa3JQaElqd2ZMTEx3QklkNFJZc3UreUtCUHM4SGtZeStVd2tZYUxwUUlpZmNkWis2UUpBNG5JWHhKaFdyMFBRaVJZWTc1Z3hJeng4eUlkTnYydStTaWFHVVZyMXArcCtjam5TYWZjNGRlejhhNE5XQ21DQTh1MGdPM1Z8WGpCOGY1UURSZ0FEcVZ0eVh1bnlIdnhQYmNTTW8yQWp0ZjdEVWk3ZkNzdz0=/8/">
  <p style="margin: 0px; font-family: Verdana; font-size: 16px; text-align: center; color: rgb(0, 31, 63); font-weight: bold;">Get new posts by email:</p> <input name="data[Widget][email]" placeholder="Your email please" value="" style="margin: 15px 0 0 0; line-height: 38px; font-size: 16px; width: 100%; text-align: center;" type="text"> <input name="data[Widget][feed_id]" value="dWZIOCtQa3JQaElqd2ZMTEx3QklkNFJZc3UreUtCUHM4SGtZeStVd2tZYUxwUUlpZmNkWis2UUpBNG5JWHhKaFdyMFBRaVJZWTc1Z3hJeng4eUlkTnYydStTaWFHVVZyMXArcCtjam5TYWZjNGRlejhhNE5XQ21DQTh1MGdPM1Z8WGpCOGY1UURSZ0FEcVZ0eVh1bnlIdnhQYmNTTW8yQWp0ZjdEVWk3ZkNzdz0=" type="hidden">
  <input name="data[Widget][feedtype]" value="8" type="hidden"> <input value="Yes alert me on news" name="subscribe" class="sub_inp_subt" style="line-height: 38px; margin: 15px 0px 0px; width: 100%; font-size: 16px; cursor: pointer; box-shadow: 1px 1px 0px rgb(102, 102, 102) ! important; font-family: Helvetica,Arial,sans-serif; text-align: center; font-weight: bold; color: rgb(0, 31, 63); background-color: rgb(122, 131, 141);" type="submit"> </form> </div>'




# {% banner300 /img/vcc/wirex.png https://www.e-coin.io/?ref=8dc1bab8343c41049b4cb7a2f1e47b4e %}
